lib: [
  "_build/install/default/lib/Authors/META"
  "_build/install/default/lib/Authors/authors.a"
  "_build/install/default/lib/Authors/authors.cma"
  "_build/install/default/lib/Authors/authors.cmi"
  "_build/install/default/lib/Authors/authors.cmt"
  "_build/install/default/lib/Authors/authors.cmti"
  "_build/install/default/lib/Authors/authors.cmx"
  "_build/install/default/lib/Authors/authors.cmxa"
  "_build/install/default/lib/Authors/authors.ml"
  "_build/install/default/lib/Authors/authors.mli"
  "_build/install/default/lib/Authors/dune-package"
  "_build/install/default/lib/Authors/opam"
]
libexec: [
  "_build/install/default/lib/Authors/authors.cmxs"
]
doc: [
  "_build/install/default/doc/Authors/README.md"
]
